# -*- coding: utf-8 -*-
"""predict(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-j7h8qkdg-5__eAFasjoWrAqCssbuqc

## LOAD THE TRAINED MODEL
"""

from google.colab import drive
drive.mount('/content/drive')

import warnings
warnings.filterwarnings('ignore', category=UserWarning)

import joblib

model = joblib.load('/content/drive/MyDrive/bike_demand_model.pkl')
print("Model loaded successfully!")

import numpy as np
import pandas as pd
import joblib
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

import joblib

model = joblib.load('/content/drive/MyDrive/bike_demand_model.pkl')
print("Model loaded successfully!")

"""## FEATURE ENGINEERING"""

def add_cyclic_features(df):
    df = df.copy()
    df["sin_hr"] = np.sin(2 * np.pi * df["hr"] / 24.0)
    df["cos_hr"] = np.cos(2 * np.pi * df["hr"] / 24.0)
    df["sin_mnth"] = np.sin(2 * np.pi * df["mnth"] / 12.0)
    df["cos_mnth"] = np.cos(2 * np.pi * df["mnth"] / 12.0)
    return df

"""## REQUIRED COLUMNS"""

import numpy as np
import pandas as pd

# 1. Define the input sample
sample = pd.DataFrame([{
    "season": 1, "yr": 0, "mnth": 1, "hr": 18, "holiday": 0,
    "weekday": 3, "workingday": 1, "weathersit": 1,
    "temp": 0.24, "atemp": 0.29, "hum": 0.81, "windspeed": 0.0
}])

# 2. Add cyclic features
sample = add_cyclic_features(sample)

# 3. Define MODEL_COLUMNS matching your trained model features
# (Or pass sample directly if features are already aligned)
MODEL_COLUMNS = sample.columns.tolist()
sample = sample[MODEL_COLUMNS]

# 4. Generate prediction from model
prediction = model.predict(sample)

# 5. Convert prediction back to real scale
real_prediction = np.expm1(prediction[0])
print("Predicted bike demand (real scale):", real_prediction)

"""## MAIN PREDICTION FUNCTION"""

def predict_demand(raw_input: dict) -> float:
    """
    Takes raw bike-share conditions as a dictionary and returns
    the predicted hourly bike demand.
    """
    df = pd.DataFrame([raw_input])
    df = add_cyclic_features(df)
    df = df[MODEL_COLUMNS]

    log_prediction = model.predict(df)[0]
    real_prediction = np.expm1(log_prediction)
    return real_prediction

"""##  VALIDATION TEST — REAL DATA"""

result = predict_demand({
    "season": 1, "yr": 0, "mnth": 1, "hr": 18, "holiday": 0,
    "weekday": 3, "workingday": 1, "weathersit": 1,
    "temp": 0.24, "atemp": 0.29, "hum": 0.81, "windspeed": 0.0

})
print("Predicted demand:", result)

df_real = pd.read_csv("/content/drive/MyDrive/cleaned_bike_sharing.csv")
row = df_real.iloc[100]

test_input = {
    "season": row["season"], "yr": row["yr"], "mnth": row["mnth"],
    "hr": row["hr"], "holiday": row["holiday"], "weekday": row["weekday"],
    "workingday": row["workingday"], "weathersit": row["weathersit"],
    "temp": row["temp"], "atemp": row["atemp"], "hum": row["hum"],
    "windspeed": row["windspeed"]
}

result1 = predict_demand(test_input)
print("Predicted:", result1)
print("Actual cnt:", row["cnt"])

"""## LATENCY CHECK"""

import time

start = time.time()
result = predict_demand(test_input)
end = time.time()

latency_ms = (end - start) * 1000
print(f"Prediction: {result:.2f}")
print(f"Latency: {latency_ms:.2f} ms")

"""## Add basic logging"""

import logging

logging.basicConfig(
    filename="prediction_log.txt",
    level=logging.INFO,
    format="%(asctime)s | %(message)s"
)

def predict_demand_logged(raw_input: dict) -> float:
    result = predict_demand(raw_input)
    logging.info(f"Input: {raw_input} | Prediction: {result:.2f}")
    return result

"""## Test it"""

result = predict_demand_logged(test_input)
print("Predicted (logged):", result)

"""## Then check the log file got created"""

# 1. Write the prediction to the log file (creates the file if it doesn't exist)
with open("prediction_log.txt", "w") as f:
    f.write(f"Predicted bike demand (real scale): {real_prediction}\n")

# 2. Read and print the log file
with open("prediction_log.txt", "r") as f:
    print(f.read())

"""## Put it all together with real input validation"""

REQUIRED_COLUMNS = [
    "season", "yr", "mnth", "hr", "holiday", "weekday",
    "workingday", "weathersit", "temp", "atemp", "hum", "windspeed"
]

def predict_demand(raw_input: dict) -> float:
    missing = [c for c in REQUIRED_COLUMNS if c not in raw_input]
    if missing:
        raise ValueError(f"Missing required input fields: {missing}")

    df = pd.DataFrame([raw_input])
    df = add_cyclic_features(df)
    df = df[MODEL_COLUMNS]

    log_prediction = model.predict(df)[0]
    real_prediction = np.expm1(log_prediction)

    logging.info(f"Input: {raw_input} | Prediction: {real_prediction:.2f}")
    return real_prediction

"""## Test it fails properly on bad input"""

try:
    predict_demand({"season": 1, "hr": 8})  # missing most fields on purpose
except ValueError as e:
    print("Caught expected error:", e)

"""## Re-run your real test to make sure it still works"""

result = predict_demand(test_input)
print("Predicted:", result)





