# -*- coding: utf-8 -*-
"""predict(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-j7h8qkdg-5__eAFasjoWrAqCssbuqc

## LOAD THE TRAINED MODEL
"""

from google.colab import drive

# Mount Google Drive
drive.mount("/content/drive")

# File paths
MODEL_PATH = "/content/drive/MyDrive/bike_demand_model.pkl"
DATA_PATH = "/content/drive/MyDrive/cleaned_bike_sharing.csv"
LOG_PATH = "/content/drive/MyDrive/bike_demand_predictions.log"

print("Google Drive mounted successfully!")
print("Model path:", MODEL_PATH)
print("Dataset path:", DATA_PATH)
drive.mount('/content/drive')

model = joblib.load(MODEL_PATH)

print("Model loaded successfully!")

# Check whether the model stores the number of expected features
if hasattr(model, "n_features_in_"):
    print("Expected number of features:", model.n_features_in_)

"""## Define the input and model feature schema"""

# Raw input columns required from the user
REQUIRED_COLUMNS = [
    "season",
    "yr",
    "mnth",
    "hr",
    "holiday",
    "weekday",
    "workingday",
    "weathersit",
    "temp",
    "atemp",
    "hum",
    "windspeed"
]

# Final feature columns expected by the trained model
MODEL_COLUMNS = [
    "season",
    "yr",
    "mnth",
    "hr",
    "holiday",
    "weekday",
    "workingday",
    "weathersit",
    "temp",
    "atemp",
    "hum",
    "windspeed",
    "sin_hr",
    "cos_hr",
    "sin_mnth",
    "cos_mnth"
]

print("Required input columns:", len(REQUIRED_COLUMNS))
print("Model features:", len(MODEL_COLUMNS))
print("\nModel feature order:")
print(MODEL_COLUMNS)

"""## FEATURE ENGINEERING"""

def add_cyclic_features(df):
    """
    Add cyclic representations of hour and month.

    This must reproduce the same feature engineering
    used when the model was trained.
    """

    df = df.copy()

    # Cyclic encoding for hour
    df["sin_hr"] = np.sin(
        2 * np.pi * df["hr"] / 24.0
    )

    df["cos_hr"] = np.cos(
        2 * np.pi * df["hr"] / 24.0
    )

    # Cyclic encoding for month
    df["sin_mnth"] = np.sin(
        2 * np.pi * df["mnth"] / 12.0
    )

    df["cos_mnth"] = np.cos(
        2 * np.pi * df["mnth"] / 12.0
    )

    return df


print("Feature engineering function created successfully!")

"""## INPUT VALIDATION

"""

def validate_input(raw_input):
    """
    Validate required fields and basic value ranges.
    """

    # Check that input is a dictionary
    if not isinstance(raw_input, dict):
        raise TypeError("Input must be provided as a dictionary.")

    # Check for missing columns
    missing = [
        column
        for column in REQUIRED_COLUMNS
        if column not in raw_input
    ]

    if missing:
        raise ValueError(
            f"Missing required input fields: {missing}"
        )

    # Check hour
    if not 0 <= raw_input["hr"] <= 23:
        raise ValueError(
            "hr must be between 0 and 23."
        )

    # Check month
    if not 1 <= raw_input["mnth"] <= 12:
        raise ValueError(
            "mnth must be between 1 and 12."
        )

    # Check season
    if not 1 <= raw_input["season"] <= 4:
        raise ValueError(
            "season must be between 1 and 4."
        )

    # Check weekday
    if not 0 <= raw_input["weekday"] <= 6:
        raise ValueError(
            "weekday must be between 0 and 6."
        )

    # Binary columns
    binary_columns = [
        "yr",
        "holiday",
        "workingday"
    ]

    for column in binary_columns:
        if raw_input[column] not in [0, 1]:
            raise ValueError(
                f"{column} must be either 0 or 1."
            )

    # Weather situation
    if not 1 <= raw_input["weathersit"] <= 4:
        raise ValueError(
            "weathersit must be between 1 and 4."
        )

    # Normalized continuous features
    normalized_columns = [
        "temp",
        "atemp",
        "hum",
        "windspeed"
    ]

    for column in normalized_columns:
        value = raw_input[column]

        if not 0 <= value <= 1:
            raise ValueError(
                f"{column} must be between 0 and 1."
            )

    return True


print("Input validation function created successfully!")

"""## LOGGING CONFIGURATION"""

# Create a file handler so predictions are stored
file_handler = logging.FileHandler(
    LOG_PATH,
    mode="a"
)

file_handler.setLevel(logging.INFO)

# Define log format
formatter = logging.Formatter(
    "%(asctime)s | %(levelname)s | %(message)s"
)

file_handler.setFormatter(formatter)

# Create logger
logger = logging.getLogger("bike_demand_mle")
logger.setLevel(logging.INFO)

# Prevent duplicate handlers if the notebook is re-run
if not logger.handlers:
    logger.addHandler(file_handler)

print("Logging configured successfully!")
print("Log file:", LOG_PATH)

open("prediction_log.txt", "w")

"""## MAIN PREDICTION FUNCTION"""

def predict_demand(raw_input):
    """
    Predict hourly bike demand.

    Steps:
    1. Validate input
    2. Convert input to DataFrame
    3. Apply feature engineering
    4. Arrange features in correct order
    5. Generate model prediction
    6. Convert log prediction back to real scale
    7. Log the prediction
    """

    # --------------------------------------
    # STEP 1: Validate input
    # --------------------------------------
    validate_input(raw_input)

    # --------------------------------------
    # STEP 2: Convert dictionary to DataFrame
    # --------------------------------------
    df = pd.DataFrame([raw_input])

    # --------------------------------------
    # STEP 3: Apply feature engineering
    # --------------------------------------
    df = add_cyclic_features(df)

    # --------------------------------------
    # STEP 4: Arrange features correctly
    # --------------------------------------
    df = df[MODEL_COLUMNS]

    # --------------------------------------
    # STEP 5: Generate prediction
    # --------------------------------------
    log_prediction = model.predict(df)[0]

    # --------------------------------------
    # STEP 6: Convert log prediction
    # back to original scale
    # --------------------------------------
    real_prediction = np.expm1(log_prediction)

    # Make sure prediction is not negative
    real_prediction = max(0.0, real_prediction)

    # --------------------------------------
    # STEP 7: Operational logging
    # --------------------------------------
    logger.info(
        f"Input: {raw_input} | "
        f"Prediction: {real_prediction:.2f}"
    )

    return real_prediction


print("Prediction function created successfully!")

"""## PREDICTION TEST"""

test_input = {
    "season": 1,
    "yr": 0,
    "mnth": 1,
    "hr": 8,
    "holiday": 0,
    "weekday": 3,
    "workingday": 1,
    "weathersit": 1,
    "temp": 0.25,
    "atemp": 0.29,
    "hum": 0.81,
    "windspeed": 0.0
}

prediction = predict_demand(test_input)

print("Input:")
print(test_input)

print("\nPredicted bike demand:")
print(f"{prediction:.2f}")

"""## REAL-DATA PIPELINE SANITY TEST"""

# Load cleaned dataset
df_real = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Dataset shape:", df_real.shape)

# Select one real row
row = df_real.iloc[100]

# Create input using the same features used by the model
real_input = {
    "season": row["season"],
    "yr": row["yr"],
    "mnth": row["mnth"],
    "hr": row["hr"],
    "holiday": row["holiday"],
    "weekday": row["weekday"],
    "workingday": row["workingday"],
    "weathersit": row["weathersit"],
    "temp": row["temp"],
    "atemp": row["atemp"],
    "hum": row["hum"],
    "windspeed": row["windspeed"]
}

# Generate prediction
predicted_value = predict_demand(real_input)

# Actual value from dataset
actual_value = row["cnt"]

print("\n----- REAL DATA TEST -----")
print("Row number:", 100)
print(f"Predicted demand: {predicted_value:.2f}")
print(f"Actual demand:    {actual_value:.2f}")

"""## REAL-DATA ERROR CHECK"""

absolute_error = abs(
    actual_value - predicted_value
)

print("Actual demand:", round(actual_value, 2))
print("Predicted demand:", round(predicted_value, 2))
print("Absolute error:", round(absolute_error, 2))

"""## LATENCY PREDICTION"""

start_time = time.perf_counter()

prediction = predict_demand(real_input)

end_time = time.perf_counter()

latency_ms = (
    end_time - start_time
) * 1000

print("Prediction:", f"{prediction:.2f}")
print("Inference latency:", f"{latency_ms:.2f} ms")

logger.info(
    f"MONITORING | "
    f"Average latency: {average_latency:.2f} ms | "
    f"Minimum latency: {minimum_latency:.2f} ms | "
    f"Maximum latency: {maximum_latency:.2f} ms"
)

print("Monitoring information logged successfully!")

print("\nPerformance summary:")
print(f"Average latency: {average_latency:.2f} ms")
print(f"Minimum latency: {minimum_latency:.2f} ms")
print(f"Maximum latency: {maximum_latency:.2f} ms")

"""## VERIFY LOG FILE"""

try:
    with open(LOG_PATH, "r") as file:
        log_content = file.read()

    print("Log file created successfully!\n")
    print("----- LAST LOG ENTRIES -----")

    # Display only the last 10 lines
    log_lines = log_content.strip().split("\n")

    for line in log_lines[-10:]:
        print(line)

except FileNotFoundError:
    print("Log file was not found.")

"""## FINAL END-TO-END TEST"""

print("==========================================")
print("     BIKE DEMAND MLE PIPELINE TEST")
print("==========================================")

# 1. Validate input
validate_input(real_input)
print("✓ Input validation passed")

# 2. Generate prediction
final_prediction = predict_demand(real_input)
print("✓ Model inference passed")

# 3. Check prediction
assert np.isfinite(final_prediction), \
    "Prediction is not a valid number."

assert final_prediction >= 0, \
    "Prediction cannot be negative."

print("✓ Prediction validation passed")

# 4. Check latency
assert average_latency >= 0, \
    "Latency cannot be negative."

print("✓ Latency test passed")

print("\n------------------------------------------")
print("FINAL PREDICTION:", f"{final_prediction:.2f}")
print("AVERAGE LATENCY:", f"{average_latency:.2f} ms")
print("------------------------------------------")



